spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://10.168.68.71:3306/user?useUnicode=true&characterEncoding=utf8&autoReconnect=true"
    username: "root"
    password: "123456"
  jpa:
    hibernate.ddl-auto: "update"
    show-sql: true