version: "3"
services:
  otel-web-client:
    image: xiaoweiwang/otel-web-client:latest
    volumes:
       - ./application.yml:/app/application.yml
    environment:
      - JVM_OPTS=-Dotel.traces.exporter=otlp -Dotel.metrics.exporter=otlp -Dotel.exporter.otlp.endpoint=http://localhost:4317 -Dotel.service.name=user-client
      - JAVA_OPTS="--spring.config.location=/app/appliaction.yml"
    restart: on-failure
    ports:
        - "8081:8081"
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/loki/api/v1/push'





