global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3200' ]
  - job_name: 'pushgateway'
    honor_labels: true
    scrape_interval: 60s
    static_configs:
      - targets: [ 'pushgateway:9091' ]
  - job_name: 'otel-collector'
    honor_labels: true
    scrape_interval: 60s
    static_configs:
      - targets: [ 'otel-collector:9098' ]
      - targets: [ 'otel-collector:8888' ]
