version: "3"
services:
  otel-web-client:
    image: xiaoweiwang/otel-web-client:latest
    volumes:
       - ./appliaction.yml:/app/appliaction.yml
    environment:
      - JVM_OPTS=-Dotel.traces.exporter=otlp,logging -Dotel.metrics.exporter=otlp -Dotel.exporter.otlp.endpoint=http://loaclhost:4317 -Dotel.service.name=user-client
      - JAVA_OPTS=--spring.config.location=/app/appliaction.yml
    ports:
        - "8080:8080"
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"



